### ISSUE TITLE
Add HidePlayerDialog

### ISSUE THREAD

**Issue by x-MV** [AGraber/samp-async-dialogs#3]

**Comment by TommyB123** [comment]
Why do you need this? If you need to close a dialog, you can simply run `ShowPlayerDialog(playerid, -1, DIALOG_STYLE_MSGBOX, "", "", "", "");`

**Comment by AGraber** [comment]
^^

**Comment by x-MV** [comment]
@TommyB123 Yes, but if I do like that include going to wait for dialogs response.

**Comment by AGraber** [comment]
The include cleans up itself if it finds an unused task later on when trying to create one

https://github.com/AGraber/samp-async-dialogs/blob/1f285193c4b012ad135533b3104c1bb11dcb04db/async-dialogs.inc#L50-L53
